# -*- coding: utf-8 -*-
"""Quickbill.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJ_Hj9fPJNqWK_SVy0SxEWGvZiXSF1XK
"""

amount = float(input("enter total amount"))
num_people = int(input("enter number of people"))
tip_percent = float(input("enter tip percentage"))
def split_bill(total_amount, num_people, tip_percent=0):
    tip = (tip_percent / 100) * total_amount
    total_with_tip = total_amount + tip
    share = total_with_tip / num_people
    return round(share, 2)
'''
# Example run
amount = 1000
people = 4
tip = 10
'''
each_share = split_bill(amount, people, tip)
print(f"Each person should pay: ₹{each_share}")